### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by raxod502** [hmc-portal2/hmc-scheduler#4]
Currently there is no license, meaning it is technically against copyright law to reuse any part of this code in another project. An open-source license like MIT would be very nice.

**Comment by hmc-cs-gyancey** [comment]
Good point.  I just reached out to all of the project's contributors, and am planning to use the Apache 2.0 license as soon as I can get everyone to agree to it.

**Comment by g-rocket** [comment]
Good point.  I just reached out to all of the project's contributors, and am planning on applying the MIT license as soon as they all get back to me.

**Comment by g-rocket** [comment]
Fixed by a80d22

**Comment by raxod502** [comment]
Thanks!
